
name: Git Actions Demo
on: [push]
jobs:
 Explore-GitHub-Actions:
   runs-on: windows-latest
   steps:
     - uses: actions/checkout@v2
     - run: echo "The job was automatically triggered by a ${{ github.event_name }} event"
     - run: python main.py
     - run: node jsCodingTask\challenge1.js
     - run: node jsCodingTask\challenge2.js
     - run: node jsCodingTask\challenge3.js
     - run: node jsCodingTask\challenge4.js

